// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2XXPvxEJuzaQjUDi_4KHA31jYQuRXyjs',
    appId: '1:777548719906:android:191c519f65d243ea0be77b',
    messagingSenderId: '777548719906',
    projectId: 'food-for-all-app-390818',
    databaseURL: 'https://food-for-all-app-390818-default-rtdb.firebaseio.com',
    storageBucket: 'food-for-all-app-390818.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0lgZMMMsWDfHFTALafHTl1axdU94A6Vw',
    appId: '1:777548719906:ios:6e1e516a59c440970be77b',
    messagingSenderId: '777548719906',
    projectId: 'food-for-all-app-390818',
    databaseURL: 'https://food-for-all-app-390818-default-rtdb.firebaseio.com',
    storageBucket: 'food-for-all-app-390818.appspot.com',
    iosClientId: '777548719906-7615lt1fsd463hics2svpliutct2qg2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffaApp',
  );
}
